### ISSUE TITLE
提一下bug，博主看下

### ISSUE THREAD

**Issue by mycold** [fly803/BaseProject#4]
1、网络请求接口已经废弃
2、分配率测试界面测试按钮点击crash
3、继承basefragment按钮点击crash
4、ui小控件按钮点击crash
5、运行时权限喝文件图像操作暂时无功能可测

**Comment by fly803** [comment]
1.网络请求接口没有废弃呀，你说的废弃是什么意思，你加QQ群，或者我QQ具体在沟通一下。QQ：356576318 QQ群：688700847
2.你说的那个按钮没有具体的功能，我注释了，不会crash了
3.说的哪个按钮，这个也要在qq在沟通一下。
4.ui小部件的功能还没有具体功能，这个疏忽了，我修改了，不会crash了
5.运行时权限的测试就是会有个弹窗，这个6.0才系统才出现，你手机是不是不是6.0以上系统。文件图像测试，界面上没有什么功能，主要是会保持一个文件到指定目录，和这个你具体看一下代码。
你加QQ：356576318 QQ群：688700847，具体在沟通一下吧。
